knife:
  type: AgentRigid
  params:
    collide_type: grid
  effectors:
    - type: Rigid
      params:
        init_pos: [0, 0, 0]
        init_euler: [0.0, 0.0, 0.0]
        action_dim: 3
        action_type: abs
        action_scale_v_rel: [0.3, 0.3, 0]
        action_scale_v_abs: [1.57, 1.57, 0]
        action_p_lower: [0.45, -1.0, -1.0]
        action_p_upper: [0.55, 1.0, 1.0]
        step_length: 0.004
      mesh:
        file: knife.obj
        use_knife_sdf: True
        normalize: False
        scale: [0.5, 0.3, 0.5]
        pos: [0.0, 0.018, 0.0575]
        euler: [0.0, 0.0, 0.0]
        material: KNIFE
        
      boundary:
        type: cube
        lower: [-0.5, -0.5, -0.5]
        upper: [0.95, 0.95, 0.95]
